### ISSUE TITLE
Allow certificates to be replaced.

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#1]
...Migrated from [Ignite Jira OF-1646](https://issues.igniterealtime.org/browse/OF-1646)...

Currently, the certificate manager plugin adds certificates to a keystore, leaving pre-existing certificates in place. It should be possible to replace pre-existing certificates, especially as some JREs are known to semi-randomly choose just one of the available certificates.

**Comment by wrooot** [comment]
https://github.com/igniterealtime/Openfire/pull/1236
