### ISSUE TITLE
should not import more than once per iteration.

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#2]
...Migrated from [Ignite Jira OF-1611](https://issues.igniterealtime.org/browse/OF-1611)...

The Certificate Manager plugin imports private key and certificate updates. When successful, the plugin often imports the same set more than once. It should import it only once.

The effects of this bug appear to be negligible: at worst, connection listeners are reconfigured (reset) more than once, but these actions should all take place in the same fraction of a second.

**Comment by guusdk** [comment]
This change was already implemented. I think I forgot to close that issue when I did.
