### ISSUE TITLE
optionally use pass phrase for private key

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#3]
...Migrated from [Ignite Jira OF-1610](https://issues.igniterealtime.org/browse/OF-1610)...

The Certificate Manager plugin loads a certificate chain and private key from a file on the file system. Currently, the private key cannot be protected by a passphrase, for the plugin to be able to process it.

It should be possible to configure the plugin with a private key passphrase.

**Comment by guusdk** [comment]
This change was already implemented. I think I forgot to close that issue when I did.
