### ISSUE TITLE
grace period for file system changes should be respected.

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#4]
...Migrated from [Ignite Jira OF-1609](https://issues.igniterealtime.org/browse/OF-1609)...

The Certificate Manager plugin is triggered by changes on the file system. It currently is triggered when two files are changed (including a private key, and a certificate chain). To allow for an administrator to manually copy these files, a grace period is observed in which both files must be added/modified. A bug prevents this grace period from working correctly, which results in the plugin not picking up file changes unless both files are modified at almost the same timestamp (mileage may vary depending on OS-characteristics).

**Comment by guusdk** [comment]
This change was already implemented. I think I forgot to close that issue when I did.
