### ISSUE TITLE
Facilitate backups for certificate stores

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#5]
...Migrated from [Ignite Jira OF-1608](https://issues.igniterealtime.org/browse/OF-1608)...

The Certificate Manager plugin modifies the content of our keystores. Before it makes any changes, it should create backups of the original files.

The ability to create backups should be something that's native to Openfire.

**Comment by guusdk** [comment]
This change was already implemented. I think I forgot to close that issue when I did.
