### ISSUE TITLE
chain should contain more than one certificate

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-certificateManager-plugin#6]
...Migrated from [Ignite Jira OF-1607](https://issues.igniterealtime.org/browse/OF-1607)...

The certificate manager plugin watches a directory. When files appear in that directory, the plugin attempts to determine what the file content is.

To detect a certificate chain, it determines if the file content consists of PEM representations of certificates. The detection currently succeeds if there's one such representation.

Instead, a chain can be expected to consist of more than one certificate. The plugin should, by default, not consider files that consist of one certificate to be a 'chain'.

**Comment by guusdk** [comment]
This change was already implemented. I think I forgot to close that issue when I did.
